#ifndef CUSTOM_ICONS_DEF_H
#define CUSTOM_ICONS_DEF_H

#define CUST_ICON_BIOHAZARD "\xEF\x9E\x80"
#define CUST_ICON_CAT "\xEF\x9A\xBE"
#define CUST_ICON_CLAPPERBOARD "\xEE\x84\xB1"
#define CUST_ICON_COW "\xEF\x9B\x88 "
#define CUST_ICON_CROW "\xEF\x94\xA0"
#define CUST_ICON_FLASK_VIAL "\xEE\x93\xB3 "
#define CUST_ICON_GHOST "\xEF\x9B\xA2 "
#define CUST_ICON_HAND_FIST "\xEF\x9B\x9E "
#define CUST_ICON_HAND_MIDDLEFINGER "\xEF\xA0\x86"
#define CUST_ICON_METEOR "\xEF\x9D\x93 "
#define CUST_ICON_PEACE "\xEF\x99\xBC"
#define CUST_ICON_POO "\xEF\x8B\xBE"
#define CUST_ICON_SKULL "\xEF\x95\x8C"
#endif