name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CPPUTEST_HOME: /usr
  
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Install cpputest
      run: sudo apt install -y cpputest
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run tests
      working-directory: ./Code/Encoder_Controller/tests
      run: make test
    - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: './Code/Encoder_Controller/tests/*.xml'
