name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CPPUTEST_HOME: /usr
  
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: install cpputest
      run: sudo apt install -y cpputest
    - uses: actions/checkout@v4
    - name: Run tests
      working-directory: ./Code/Encoder_Controller/tests
      run: make test
