name: BuildPolyhymnia
permissions:
  contents: read

on:
  push:
    branches: [ "main", "port_to_platformio" ]
  pull_request:
    branches: [ "main" ]

env:
  CPPUTEST_HOME: /usr
  
jobs:
  build_polyhymnia:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        working-directory: ./Code/Polyhymnia/
        run: pio run -e teensy41